### ISSUE TITLE
`fela-plugin-embedded` not published on NPM?

### ISSUE THREAD

**Issue by kompot** [rofrischmann/fela#283]
`https://www.npmjs.com/search?q=fela-plugin-embedded` says that there's no such package available.

Found that by trying to do `yarn install` in `packages/example-react`.

**Comment by tajo** [comment]
@kompot **it was not published yet**, sorry for the confusion. For now, you can do this:

```
yarn install
yarn run bootstrap
cd packages/example-react
npm start
```

It's using [lerna](https://lernajs.io/) to symlink packages locally (the bootstrap step).

**Comment by kompot** [comment]
That gives this

```
yarn start v0.24.6
$ concurrently --kill-others "npm run client" "babel-node server.js"
[0]
[0] > example-react@1.0.0 client /Users/kompot/tmp/fela/packages/example-react
[0] > NODE_ENV=development webpack-dev-server
[0]
[1] module.js:487
[1]     throw err;
[1]     ^
[1]
[1] Error: Cannot find module 'react-fela'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/kompot/tmp/fela/packages/example-react/server.js:5:1)
[1]     at Module._compile (module.js:569:30)
[1]     at loader (/Users/kompot/tmp/fela/packages/example-react/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/kompot/tmp/fela/packages/example-react/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1] babel-node server.js exited with code 1
--> Sending SIGTERM to other processes..
[0] Project is running at http://localhost:8080/
[0] webpack output is served from /
[0] npm run client exited with code 0
error Command failed with exit code 1.
```
and `yarn add react-fela` in `packages/example-react` fails because `Couldn't find package "fela-plugin-embedded" on the "npm" registry`

**Comment by tajo** [comment]
I forgot one step, you should do:

```
yarn install
yarn run bootstrap
yarn run build
cd packages/example-react
yarn start
```

Once everything is published, you will do only

```
cd packages/example-react
yarn install
yarn start
```
