### ISSUE TITLE
Issues with testing nested components

### ISSUE THREAD

**Issue by nadzic** [rofrischmann/fela#349]
Hi, I am trying to test nested components with react-test-rederer (I also tried shallow and mount from enzyme). For example.. testing components which do not have subcomponents works fine for me, but I'm having problem if the component has more subcomponents

Here is the error which im getting:

 FAIL  src/components/common/organisms/Footer.test.js
  ● Footer › should render component

    TypeError: Cannot convert a Symbol value to a string
      
      at Object._renderStyleToClassNames (node_modules/fela/lib/createRenderer.js:185:64)
      at Object.renderRule (node_modules/fela/lib/createRenderer.js:51:23)
      at FelaComponent (node_modules/fela/lib/bindings/createComponentFactory.js:83:51)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:305:16
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper._constructComponentWithoutOwner (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:304:14)
      at ReactCompositeComponentWrapper._constructComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:279:21)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:187:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:45:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:370:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:257:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:45:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:370:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:257:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:45:35)
      at mountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:55:31)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:143:20)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:143:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:128:18)
      at felaSnapshot (src/components/common/organisms/Footer.test.js:17:5)
      at Object.it (src/components/common/organisms/Footer.test.js:29:22)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)

.... Do you have any clue what should I do about this converting ?
Kinds, Nik

**Version**: 3.0.x
**Environment**: DOM / Server / Both
**Type**: Bug / Feature / Infrastructure / Docs / General

-------------------
#### Description
Please try to add as much detail as possible.

#### Steps to reproduce
1. First step
2. Second step

#### Expected Behavior
```javascript
// your code here
```

#### Actual Behavior
```javascript
My component: 

import React from 'react'
import { createComponent as cc } from 'react-fela'
import { Link } from 'react-router-dom'
import { colors } from '../../../constants/Colors'

const FooterStyle = cc(_ => ({
  position: 'fixed',
  bottom: '0',
  width: '100%',
  height: '70px',
  backgroundColor: colors.grey5,
  fontFamily: 'Ubuntu',
  fontSize: '13px',
  lineHeight: '70px',
  textAlign: 'center',
  color: colors.white,
  flexShrink: 0
}))

const FooterCenter = cc(
  _ => ({
    opacity: 0.6,
    color: colors.white,
    textDecoration: 'none'
  }),
  'a',
  ['href']
)

const FooterLeft = cc(_ => ({
  opacity: 0.6,
  float: 'left',
  paddingLeft: '130px',
  color: colors.white,
  textDecoration: 'none'
}))

const FooterRight = cc(_ => ({
  opacity: 0.6,
  float: 'right',
  color: colors.white,
  textDecoration: 'none'
}))

const Footer = _ =>
  <FooterStyle>
    <Link to=''>
      <FooterLeft>© 2017 CherryDeck. All rights reserved.</FooterLeft>
    </Link>

    <Link to='imprint'>
      <FooterRight style={{ marginRight: '130px' }}>Imprint</FooterRight>
    </Link>
    <FooterRight style={{ margin: '0 13px' }}>•</FooterRight>
    <Link to='privacy-policy'>
      <FooterRight>Data Protection Policy</FooterRight>
    </Link>

    <FooterCenter href={'mailto:hello@cherrydeck.com'}>
      hello@cherrydeck.com
    </FooterCenter>
  </FooterStyle>

export default Footer


My test:

import React from 'react'
import renderer from 'react-test-renderer'
import { createRenderer } from 'fela'
import { Provider, createComponent } from 'react-fela'
import { shallow } from '../../../utils/FelaShallow'
import Footer from './Footer'

const FooterCmp = createComponent(Footer)

const prettifyFelaString = str => str.replace(/\.[a-z]+/g, '\n    $&')

function felaSnapshot(component) {
  const felaRenderer = createRenderer()

  return {
    component: renderer
      .create(
        <Provider renderer={felaRenderer}>
          {component}
        </Provider>
      )
      .toJSON(),
    styles: prettifyFelaString(felaRenderer.renderToString())
  }
}

describe('Footer', () => {
  it('should render component', () => {
    const snapshot = felaSnapshot(<FooterCmp/>)
  })
})
```

#### Proposal
Any information on how this might be achieved.

**Code Example**:
```javascript
// your proposal here
```

**Comment by rofrischmann** [comment]
```js
const FooterCmp = createComponent(Footer)
```

Why would you want to wrap that one again with createComponent? createComponent turns rule functions to styled components, but Footer is a simple React component, that's why it doesn't work. It tries to use the actual component as a style function which obviously fails.
