### ISSUE TITLE
`example-preact` error: `Cannot find module 'react'` 

### ISSUE THREAD

**Issue by timswalling** [rofrischmann/fela#414]
**Version**: 6.0.0
**Environment**: Both
**Type**: Bug

-------------------
#### Description
I receive a "Cannot find module 'react'" error when I run the provided Preact example. This appears the be caused by [Recompose](https://github.com/acdlite/recompose), which requires React.

#### Steps to reproduce
1. Clone the Fela repository
2. Navigate to `packages/example-preact` and run `yarn`
3. Run `yarn start`

#### Expected Behavior
The example will start without errors.

#### Actual Behavior
The example fails to start with an error:
```
Error: Cannot find module 'react'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/Users/timswalling/Code/fela/packages/example-preact/node_modules/recompose/cjs/Recompose.js:7:13)
     at Module._compile (module.js:570:32)
     at Module._extensions..js (module.js:579:10)
     at Object.require.extensions.(anonymous function) [as .js] (/Users/timswalling/Code/fela/packages/example-preact/node_modules/babel-register/lib/node.js:152:7)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
```

**Comment by timswalling** [comment]
Adding an alias to the Webpack config (as per Recompose docs) fixes the issue in the client, but not on the server. I tried a couple of different module aliasing options for Babel, but I couldn't get anything elegant to work.

I'm happy to update the example to use a webpack build for client and server if you're happy with that.

**Comment by rofrischmann** [comment]
Oh I was not aware that recompose requires React, the functionality which we're using does not need React, so we mind find a smaller dependency in general.
